---
# file: provisioning/tasks/main.yml

- name: Update Package Cache
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade Out-of-Date Packages
  ansible.builtin.apt:
    upgrade: true

- name: Install Core Packages via Package Manager
  ansible.builtin.apt:
    name:
      - git
      - git-lfs
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - vim-nox
    state: present
